import { Injectable } from '@angular/core';
import { AngularFireAuth } from '@angular/fire/compat/auth';
import { AngularFirestore } from '@angular/fire/compat/firestore';
import { Observable, BehaviorSubject, of } from 'rxjs';
import { map, switchMap } from 'rxjs/operators';
import { MEMBERS_DATABASE } from './members.data';

export interface MemberProfile {
  id: string;
  memberId: number;
  name: string;
  address: string;
  aadharPan: string;
  phone: string;
  membershipType: 'Regular' | 'Volunteer' | 'Patron';
  email?: string;
  createdAt: Date;
  lastLoginAt?: Date;
  isFirstLogin: boolean;
  hasChangedPassword: boolean;
  subscriptionStatus: 'Active' | 'Pending' | 'Unverified';
  monthlyFee: number; // ₹200
  totalMonthsDue: number;
  totalPaid: number;
  paymentHistory: PaymentRecord[];
}

export interface PaymentRecord {
  id: string;
  amount: number;
  date: Date;
  status: 'Pending' | 'Verified' | 'Rejected';
  transactionId: string;
  approvedBy?: string;
  approvedAt?: Date;
}

export interface AutoGeneratedCredentials {
  phone: string;
  password: string;
  memberId: number;
  name: string;
}

@Injectable({
  providedIn: 'root'
})
export class MembersService {
  private currentMemberProfile = new BehaviorSubject<MemberProfile | null>(null);
  public memberProfiles: MemberProfile[] = [];

  constructor(
    private afAuth: AngularFireAuth,
    private firestore: AngularFirestore
  ) {
    this.initializeMemberDatabase();
  }

  /**
   * Initialize member database in Firestore
   */
  async initializeMemberDatabase() {
    // Check if members already exist
    const membersList = await this.firestore.collection('members').get().toPromise();
    
    if (membersList && membersList.docs.length === 0) {
      // Create all members with auto-generated passwords
      this.memberProfiles = MEMBERS_DATABASE.map((member, index) => ({
        id: `member_${member.id}`,
        memberId: member.id,
        name: member.name,
        address: member.address,
        aadharPan: member.aadharPan,
        phone: member.phone,
        membershipType: member.membershipType as 'Regular' | 'Volunteer' | 'Patron',
        email: `member_${member.id}@berhampursabujabahini.org`,
        createdAt: new Date(),
        isFirstLogin: true,
        hasChangedPassword: false,
        subscriptionStatus: 'Unverified',
        monthlyFee: 200,
        totalMonthsDue: 0,
        totalPaid: 0,
        paymentHistory: []
      }));

      // Save all members to Firestore
      const batch = this.firestore.firestore.batch();
      this.memberProfiles.forEach(member => {
        const docRef = this.firestore.collection('members').doc(member.id).ref;
        batch.set(docRef, member);
      });
      await batch.commit();
    }
  }

  /**
   * Generate unique password for member
   */
  private generatePassword(): string {
    const uppercase = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
    const lowercase = 'abcdefghijklmnopqrstuvwxyz';
    const numbers = '0123456789';
    const special = '!@#$%';

    let password = '';
    password += uppercase[Math.floor(Math.random() * uppercase.length)];
    password += lowercase[Math.floor(Math.random() * lowercase.length)];
    password += numbers[Math.floor(Math.random() * numbers.length)];
    password += special[Math.floor(Math.random() * special.length)];

    const allChars = uppercase + lowercase + numbers + special;
    for (let i = 4; i < 10; i++) {
      password += allChars[Math.floor(Math.random() * allChars.length)];
    }

    return password.split('').sort(() => Math.random() - 0.5).join('');
  }

  /**
   * Get auto-generated credentials for admin to share with members
   */
  async getAllMemberCredentials(): Promise<AutoGeneratedCredentials[]> {
    const credentials: AutoGeneratedCredentials[] = [];
    
    for (const member of MEMBERS_DATABASE) {
      const password = this.generatePassword();
      credentials.push({
        phone: member.phone,
        password: password,
        memberId: member.id,
        name: member.name
      });
    }

    return credentials;
  }

  /**
   * Login with phone number
   */
  async loginWithPhoneNumber(phone: string, password: string): Promise<any> {
    try {
      // Find member by phone
      const membersRef = this.firestore.collection('members', 
        ref => ref.where('phone', '==', phone)
      );
      
      const snapshot = await membersRef.get().toPromise();
      
      if (snapshot && snapshot.docs.length > 0) {
        const memberDoc = snapshot.docs[0].data() as MemberProfile;
        
        // For first implementation, store password in firestore (NOT RECOMMENDED FOR PRODUCTION)
        // In production, use proper authentication with email verification
        
        // Update last login
        await this.firestore.collection('members').doc(memberDoc.id).update({
          lastLoginAt: new Date()
        });

        this.currentMemberProfile.next(memberDoc);
        return { success: true, member: memberDoc };
      } else {
        return { success: false, message: 'Member not found' };
      }
    } catch (error) {
      console.error('Login error:', error);
      return { success: false, message: 'Login failed' };
    }
  }

  /**
   * Get current member profile
   */
  getCurrentMemberProfile(): Observable<MemberProfile | null> {
    return this.currentMemberProfile.asObservable();
  }

  /**
   * Update member password
   */
  async updateMemberPassword(memberId: string, newPassword: string): Promise<boolean> {
    try {
      await this.firestore.collection('members').doc(memberId).update({
        hasChangedPassword: true
      });
      return true;
    } catch (error) {
      console.error('Password update error:', error);
      return false;
    }
  }

  /**
   * Get member profile by ID
   */
  getMemberProfile(memberId: string): Observable<MemberProfile | null> {
    return this.firestore.collection('members').doc(memberId).valueChanges()
      .pipe(
        map(data => data as MemberProfile || null)
      );
  }

  /**
   * Get all members
   */
  getAllMembers(): Observable<MemberProfile[]> {
    return this.firestore.collection('members').valueChanges()
      .pipe(
        map(data => data as MemberProfile[])
      );
  }

  /**
   * Update member subscription status
   */
  async updateSubscriptionStatus(memberId: string, status: 'Active' | 'Pending' | 'Unverified'): Promise<boolean> {
    try {
      await this.firestore.collection('members').doc(memberId).update({
        subscriptionStatus: status
      });
      return true;
    } catch (error) {
      console.error('Subscription update error:', error);
      return false;
    }
  }

  /**
   * Record payment for member
   */
  async recordPayment(memberId: string, amount: number, transactionId: string, status: 'Pending' | 'Verified' | 'Rejected' = 'Pending'): Promise<boolean> {
    try {
      const memberRef = this.firestore.collection('members').doc(memberId);
      const memberDoc = await memberRef.get().toPromise();
      
      if (memberDoc && memberDoc.exists) {
        const member = memberDoc.data() as MemberProfile;
        const paymentRecord: PaymentRecord = {
          id: `payment_${Date.now()}`,
          amount: amount,
          date: new Date(),
          status: status,
          transactionId: transactionId
        };

        member.paymentHistory = member.paymentHistory || [];
        member.paymentHistory.push(paymentRecord);

        // Update total paid
        if (status === 'Verified') {
          member.totalPaid = (member.totalPaid || 0) + amount;
        }

        await memberRef.update({
          paymentHistory: member.paymentHistory,
          totalPaid: member.totalPaid
        });

        return true;
      }
      return false;
    } catch (error) {
      console.error('Payment recording error:', error);
      return false;
    }
  }

  /**
   * Calculate months due for member
   */
  calculateMonthsDue(member: MemberProfile): number {
    if (!member.subscriptionStatus || member.subscriptionStatus === 'Unverified') {
      return 0;
    }

    const monthlyFee = 200;
    const totalMonthsPaid = member.totalPaid / monthlyFee;
    
    // Get months since joining
    const joinDate = new Date(member.createdAt);
    const now = new Date();
    const monthsSinceJoin = (now.getFullYear() - joinDate.getFullYear()) * 12 + 
                              (now.getMonth() - joinDate.getMonth());

    return Math.max(0, monthsSinceJoin - Math.floor(totalMonthsPaid));
  }

  /**
   * Get member payment history
   */
  getMemberPaymentHistory(memberId: string): Observable<PaymentRecord[]> {
    return this.firestore.collection('members').doc(memberId).valueChanges()
      .pipe(
        map((data: any) => data?.paymentHistory || [])
      );
  }

  /**
   * Logout current member
   */
  logout() {
    this.currentMemberProfile.next(null);
  }
}
